version: "3.9"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "SQLsa736."
      ACCEPT_EULA: "Y"
    ports:
      - "14333:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./docker/sql:/docker-entrypoint-initdb.d
    networks:
      - backend

  auth-api:
    build:
      context: Auth/Auth.WebAPI
      dockerfile: Dockerfile
    container_name: auth-api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__AuthDB=Server=sqlserver;Database=AuthDB;User Id=sa;Password=SQLsa736.;TrustServerCertificate=True;
    ports:
      - "5001:80"
    networks:
      - backend

  seguros-api:
    build:
      context: Seguros/Seguros.WebAPI
      dockerfile: Dockerfile
    container_name: seguros-api
    depends_on:
      - sqlserver
      - auth-api
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__InsuranceDB=Server=sqlserver;Database=InsuranceDB;User Id=sa;Password=SQLsa736.;TrustServerCertificate=True;
      - AuthApiUrl=http://auth-api
      - Redis__ConnectionString=redis:6379
    ports:
      - "5002:80"
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
    command: redis-server --appendonly yes

networks:
  backend:

volumes:
  sql_data:
  redis_data: